server:
  port: 8181
spring:
  application:
    name: lanmao-web-bops
  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false
      write-dates-as-timestamps: false
    time-zone: GMT+08
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: 47.105.132.129:8848
